name = "agent-sdk-voice-canvas"
main = "dist/worker.js"

compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

no_bundle = true

[build]
command = "pnpm build"


[assets]
directory = "dist/static"